"""
Built-in OAuth2/OIDC provider configs (slug -> endpoints).
Used by GenericOAuth2Provider when no dedicated provider class exists.
All URLs are standard endpoints; credentials (client_id, client_secret) come from settings/DB.
"""
# Format: slug -> dict with token_url, user_info_url, authorization_url; optional user_info_map.

BUILTIN_OAUTH2_CONFIGS = {
    "microsoft": {
        "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "user_info_url": "https://graph.microsoft.com/v1.0/me",
        "authorization_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "user_info_map": {"id": "id", "email": "mail", "name": "displayName", "picture": None},
    },
    "apple": {
        "token_url": "https://appleid.apple.com/auth/token",
        "user_info_url": "",  # Apple returns user in id_token / first callback only
        "authorization_url": "https://appleid.apple.com/auth/authorize",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": None},
    },
    "twitter": {
        "token_url": "https://api.twitter.com/2/oauth2/token",
        "user_info_url": "https://api.twitter.com/2/users/me",
        "authorization_url": "https://twitter.com/i/oauth2/authorize",
        "user_info_map": {"id": "data.id", "email": None, "name": "data.name", "picture": "data.profile_image_url"},
    },
    "linkedin": {
        "token_url": "https://www.linkedin.com/oauth/v2/accessToken",
        "user_info_url": "https://api.linkedin.com/v2/userinfo",
        "authorization_url": "https://www.linkedin.com/oauth/v2/authorization",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": "picture"},
    },
    "amazon": {
        "token_url": "https://api.amazon.com/auth/o2/token",
        "user_info_url": "https://api.amazon.com/user/profile",
        "authorization_url": "https://www.amazon.com/ap/oa",
        "user_info_map": {"id": "user_id", "email": "email", "name": "name", "picture": None},
    },
    "discord": {
        "token_url": "https://discord.com/api/oauth2/token",
        "user_info_url": "https://discord.com/api/users/@me",
        "authorization_url": "https://discord.com/api/oauth2/authorize",
        "user_info_map": {"id": "id", "email": "email", "name": "username", "picture": "avatar"},
    },
    "slack": {
        "token_url": "https://slack.com/api/oauth.v2.access",
        "user_info_url": "https://slack.com/api/users.identity",
        "authorization_url": "https://slack.com/oauth/v2/authorize",
        "user_info_map": {"id": "user.id", "email": "user.email", "name": "user.name", "picture": "user.image_512"},
    },
    "spotify": {
        "token_url": "https://accounts.spotify.com/api/token",
        "user_info_url": "https://api.spotify.com/v1/me",
        "authorization_url": "https://accounts.spotify.com/authorize",
        "user_info_map": {"id": "id", "email": "email", "name": "display_name", "picture": "images[0].url"},
    },
    "yahoo": {
        "token_url": "https://api.login.yahoo.com/oauth2/get_token",
        "user_info_url": "https://api.login.yahoo.com/openid/v1/userinfo",
        "authorization_url": "https://api.login.yahoo.com/oauth2/request_auth",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": "picture"},
    },
    "gitlab": {
        "token_url": "https://gitlab.com/oauth/token",
        "user_info_url": "https://gitlab.com/api/v4/user",
        "authorization_url": "https://gitlab.com/oauth/authorize",
        "user_info_map": {"id": "id", "email": "email", "name": "name", "picture": "avatar_url"},
    },
    "bitbucket": {
        "token_url": "https://bitbucket.org/site/oauth2/access_token",
        "user_info_url": "https://api.bitbucket.org/2.0/user",
        "authorization_url": "https://bitbucket.org/site/oauth2/authorize",
        "user_info_map": {"id": "uuid", "email": None, "name": "display_name", "picture": "links.avatar.href"},
    },
    "dropbox": {
        "token_url": "https://api.dropboxapi.com/oauth2/token",
        "user_info_url": "https://api.dropboxapi.com/2/users/get_current_account",
        "authorization_url": "https://www.dropbox.com/oauth2/authorize",
        "user_info_map": {"id": "account_id", "email": "email", "name": "name.display_name", "picture": "profile_photo_url"},
    },
    "box": {
        "token_url": "https://api.box.com/oauth2/token",
        "user_info_url": "https://api.box.com/2.0/users/me",
        "authorization_url": "https://account.box.com/api/oauth2/authorize",
        "user_info_map": {"id": "id", "email": "login", "name": "name", "picture": "avatar_url"},
    },
    "paypal": {
        "token_url": "https://api-m.paypal.com/v1/oauth2/token",
        "user_info_url": "https://api-m.paypal.com/v1/identity/oauth2/userinfo",
        "authorization_url": "https://www.paypal.com/connect",
        "user_info_map": {"id": "user_id", "email": "emails[0].value", "name": "name", "picture": "picture"},
    },
    "twitch": {
        "token_url": "https://id.twitch.tv/oauth2/token",
        "user_info_url": "https://api.twitch.tv/helix/users",
        "authorization_url": "https://id.twitch.tv/oauth2/authorize",
        "user_info_map": {"id": "data[0].id", "email": "data[0].email", "name": "data[0].display_name", "picture": "data[0].profile_image_url"},
    },
    "reddit": {
        "token_url": "https://www.reddit.com/api/v1/access_token",
        "user_info_url": "https://oauth.reddit.com/api/v1/me",
        "authorization_url": "https://www.reddit.com/api/v1/authorize",
        "user_info_map": {"id": "id", "email": None, "name": "name", "picture": "icon_img"},
    },
    "tumblr": {
        "token_url": "https://api.tumblr.com/v2/oauth2/token",
        "user_info_url": "https://api.tumblr.com/v2/user/info",
        "authorization_url": "https://www.tumblr.com/oauth2/authorize",
        "user_info_map": {"id": "user.name", "email": None, "name": "user.name", "picture": None},
    },
    "meetup": {
        "token_url": "https://secure.meetup.com/oauth2/access",
        "user_info_url": "https://api.meetup.com/2/member/self",
        "authorization_url": "https://secure.meetup.com/oauth2/authorize",
        "user_info_map": {"id": "id", "email": "email", "name": "name", "picture": "photo.photo_link"},
    },
    "patreon": {
        "token_url": "https://www.patreon.com/api/oauth2/token",
        "user_info_url": "https://www.patreon.com/api/oauth2/v2/identity",
        "authorization_url": "https://www.patreon.com/oauth2/authorize",
        "user_info_map": {"id": "data.id", "email": "data.attributes.email", "name": "data.attributes.full_name", "picture": "data.attributes.image_url"},
    },
    "pinterest": {
        "token_url": "https://api.pinterest.com/v5/oauth/token",
        "user_info_url": "https://api.pinterest.com/v5/user_account",
        "authorization_url": "https://www.pinterest.com/oauth/",
        "user_info_map": {"id": "username", "email": None, "name": "username", "picture": "profile_image"},
    },
    "salesforce": {
        "token_url": "https://login.salesforce.com/services/oauth2/token",
        "user_info_url": "https://login.salesforce.com/services/oauth2/userinfo",
        "authorization_url": "https://login.salesforce.com/services/oauth2/authorize",
        "user_info_map": {"id": "user_id", "email": "email", "name": "name", "picture": "picture"},
    },
    "zendesk": {
        "token_url": "https://{subdomain}.zendesk.com/oauth/tokens",
        "user_info_url": "https://{subdomain}.zendesk.com/api/v2/users/me.json",
        "authorization_url": "https://{subdomain}.zendesk.com/oauth/authorizations/new",
        "user_info_map": {"id": "user.id", "email": "user.email", "name": "user.name", "picture": None},
    },
    "atlassian": {
        "token_url": "https://auth.atlassian.com/oauth2/token",
        "user_info_url": "https://api.atlassian.com/me",
        "authorization_url": "https://auth.atlassian.com/authorize",
        "user_info_map": {"id": "account_id", "email": "email", "name": "name", "picture": "picture"},
    },
    "notion": {
        "token_url": "https://api.notion.com/v1/oauth/token",
        "user_info_url": "https://api.notion.com/v1/users/me",
        "authorization_url": "https://api.notion.com/v1/oauth/authorize",
        "user_info_map": {"id": "id", "email": None, "name": "name", "picture": "avatar_url"},
    },
    "figma": {
        "token_url": "https://api.figma.com/v1/oauth/token",
        "user_info_url": "https://api.figma.com/v1/me",
        "authorization_url": "https://api.figma.com/v1/oauth",
        "user_info_map": {"id": "id", "email": "email", "name": "handle", "picture": "img_url"},
    },
    "linear": {
        "token_url": "https://api.linear.app/oauth/token",
        "user_info_url": "https://api.linear.app/graphql",
        "authorization_url": "https://linear.app/oauth/authorize",
        "user_info_map": {"id": "viewer.id", "email": "viewer.email", "name": "viewer.name", "picture": "viewer.avatarUrl"},
    },
    "vercel": {
        "token_url": "https://api.vercel.com/v2/oauth/access_token",
        "user_info_url": "https://api.vercel.com/v2/user",
        "authorization_url": "https://vercel.com/integrations/oauth/authorize",
        "user_info_map": {"id": "user.id", "email": "user.email", "name": "user.name", "picture": "user.image"},
    },
    "digitalocean": {
        "token_url": "https://cloud.digitalocean.com/v1/oauth/token",
        "user_info_url": "https://api.digitalocean.com/v2/account",
        "authorization_url": "https://cloud.digitalocean.com/v1/oauth/authorize",
        "user_info_map": {"id": "account.uuid", "email": "account.email", "name": None, "picture": None},
    },
    "heroku": {
        "token_url": "https://id.heroku.com/oauth/token",
        "user_info_url": "https://api.heroku.com/account",
        "authorization_url": "https://id.heroku.com/oauth/authorize",
        "user_info_map": {"id": "id", "email": "email", "name": "name", "picture": None},
    },
    "zoom": {
        "token_url": "https://zoom.us/oauth/token",
        "user_info_url": "https://api.zoom.us/v2/users/me",
        "authorization_url": "https://zoom.us/oauth/authorize",
        "user_info_map": {"id": "id", "email": "email", "name": "first_name", "picture": "pic_url"},
    },
    "adobe": {
        "token_url": "https://ims-na1.adobelogin.com/ims/token/v3",
        "user_info_url": "https://ims-na1.adobelogin.com/ims/userinfo/v2",
        "authorization_url": "https://ims-na1.adobelogin.com/ims/authorize/v2",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": "picture"},
    },
    "dribbble": {
        "token_url": "https://dribbble.com/oauth/token",
        "user_info_url": "https://api.dribbble.com/v2/user",
        "authorization_url": "https://dribbble.com/oauth/authorize",
        "user_info_map": {"id": "id", "email": None, "name": "name", "picture": "avatar_url"},
    },
    "strava": {
        "token_url": "https://www.strava.com/oauth/token",
        "user_info_url": "https://www.strava.com/api/v3/athlete",
        "authorization_url": "https://www.strava.com/oauth/authorize",
        "user_info_map": {"id": "id", "email": None, "name": "firstname", "picture": "profile"},
    },
    "soundcloud": {
        "token_url": "https://api.soundcloud.com/oauth2/token",
        "user_info_url": "https://api.soundcloud.com/me",
        "authorization_url": "https://soundcloud.com/connect",
        "user_info_map": {"id": "id", "email": None, "name": "username", "picture": "avatar_url"},
    },
    "trello": {
        "token_url": "https://api.trello.com/1/oauth/token",
        "user_info_url": "https://api.trello.com/1/members/me",
        "authorization_url": "https://trello.com/1/authorize",
        "user_info_map": {"id": "id", "email": "email", "name": "fullName", "picture": "avatarUrl"},
    },
    "asana": {
        "token_url": "https://app.asana.com/-/oauth_token",
        "user_info_url": "https://app.asana.com/api/1.0/users/me",
        "authorization_url": "https://app.asana.com/-/oauth_authorize",
        "user_info_map": {"id": "data.gid", "email": "data.email", "name": "data.name", "picture": "data.photo.image_128x128"},
    },
    "yandex": {
        "token_url": "https://oauth.yandex.com/token",
        "user_info_url": "https://login.yandex.ru/info",
        "authorization_url": "https://oauth.yandex.com/authorize",
        "user_info_map": {"id": "id", "email": "default_email", "name": "display_name", "picture": "default_avatar_id"},
    },
    "mailru": {
        "token_url": "https://oauth.mail.ru/token",
        "user_info_url": "https://oauth.mail.ru/userinfo",
        "authorization_url": "https://oauth.mail.ru/login",
        "user_info_map": {"id": "email", "email": "email", "name": "name", "picture": "image"},
    },
    "vk": {
        "token_url": "https://oauth.vk.com/access_token",
        "user_info_url": "https://api.vk.com/method/users.get",
        "authorization_url": "https://oauth.vk.com/authorize",
        "user_info_map": {"id": "response[0].id", "email": "email", "name": "response[0].first_name", "picture": "response[0].photo_200"},
    },
    "weibo": {
        "token_url": "https://api.weibo.com/oauth2/access_token",
        "user_info_url": "https://api.weibo.com/2/users/show.json",
        "authorization_url": "https://api.weibo.com/oauth2/authorize",
        "user_info_map": {"id": "idstr", "email": None, "name": "screen_name", "picture": "profile_image_url"},
    },
    "okta": {
        "token_url": "https://{domain}/oauth2/v1/token",
        "user_info_url": "https://{domain}/oauth2/v1/userinfo",
        "authorization_url": "https://{domain}/oauth2/v1/authorize",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": "picture"},
    },
    "auth0": {
        "token_url": "https://{domain}/oauth/token",
        "user_info_url": "https://{domain}/userinfo",
        "authorization_url": "https://{domain}/authorize",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": "picture"},
    },
    "keycloak": {
        "token_url": "https://{realm_url}/protocol/openid-connect/token",
        "user_info_url": "https://{realm_url}/protocol/openid-connect/userinfo",
        "authorization_url": "https://{realm_url}/protocol/openid-connect/auth",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": None},
    },
    "instagram": {
        "token_url": "https://api.instagram.com/oauth/access_token",
        "user_info_url": "https://graph.instagram.com/me",
        "authorization_url": "https://api.instagram.com/oauth/authorize",
        "user_info_map": {"id": "id", "email": None, "name": "username", "picture": None},
    },
    "snapchat": {
        "token_url": "https://accounts.snap.com/api/v2/oauth2/token",
        "user_info_url": "https://api.accounts.snap.com/api/v2/user",
        "authorization_url": "https://accounts.snap.com/oauth2/v2/authorize",
        "user_info_map": {"id": "sub", "email": "email", "name": "display_name", "picture": "picture"},
    },
    "tiktok": {
        "token_url": "https://open.tiktokapis.com/v2/oauth/token/",
        "user_info_url": "https://open.tiktokapis.com/v2/user/info/",
        "authorization_url": "https://www.tiktok.com/auth/authorize/",
        "user_info_map": {"id": "data.user.open_id", "email": None, "name": "data.user.display_name", "picture": "data.user.avatar_url"},
    },
    "evernote": {
        "token_url": "https://api.evernote.com/oauth",
        "user_info_url": "https://api.evernote.com/edam/user",
        "authorization_url": "https://www.evernote.com/OAuth.action",
        "user_info_map": {"id": "id", "email": None, "name": "name", "picture": None},
    },
    "fitbit": {
        "token_url": "https://api.fitbit.com/oauth2/token",
        "user_info_url": "https://api.fitbit.com/1/user/-/profile.json",
        "authorization_url": "https://www.fitbit.com/oauth2/authorize",
        "user_info_map": {"id": "user.encodedId", "email": "user.fullName", "name": "user.displayName", "picture": "user.avatar"},
    },
    "lastfm": {
        "token_url": "https://ws.audioscrobbler.com/2.0/",
        "user_info_url": "https://ws.audioscrobbler.com/2.0/",
        "authorization_url": "https://www.last.fm/api/auth",
        "user_info_map": {"id": "user.name", "email": None, "name": "user.name", "picture": "user.image"},
    },
    "medium": {
        "token_url": "https://api.medium.com/v1/tokens",
        "user_info_url": "https://api.medium.com/v1/me",
        "authorization_url": "https://medium.com/m/oauth/authorize",
        "user_info_map": {"id": "data.id", "email": "data.email", "name": "data.name", "picture": "data.imageUrl"},
    },
    "wordpress": {
        "token_url": "https://public-api.wordpress.com/oauth2/token",
        "user_info_url": "https://public-api.wordpress.com/rest/v1.1/me",
        "authorization_url": "https://public-api.wordpress.com/oauth2/authorize",
        "user_info_map": {"id": "ID", "email": "email", "name": "display_name", "picture": "avatar_URL"},
    },
    "deviantart": {
        "token_url": "https://www.deviantart.com/oauth2/token",
        "user_info_url": "https://www.deviantart.com/api/v1/oauth2/user/whoami",
        "authorization_url": "https://www.deviantart.com/oauth2/authorize",
        "user_info_map": {"id": "userid", "email": None, "name": "username", "picture": "usericon"},
    },
    "stackoverflow": {
        "token_url": "https://stackoverflow.com/oauth/access_token",
        "user_info_url": "https://api.stackexchange.com/2.3/me",
        "authorization_url": "https://stackoverflow.com/oauth",
        "user_info_map": {"id": "items[0].user_id", "email": "items[0].email", "name": "items[0].display_name", "picture": "items[0].profile_image"},
    },
    "imgur": {
        "token_url": "https://api.imgur.com/oauth2/token",
        "user_info_url": "https://api.imgur.com/3/account/me",
        "authorization_url": "https://api.imgur.com/oauth2/authorize",
        "user_info_map": {"id": "data.id", "email": "data.email", "name": "data.url", "picture": "data.avatar"},
    },
    "foursquare": {
        "token_url": "https://foursquare.com/oauth2/access_token",
        "user_info_url": "https://api.foursquare.com/v2/users/self",
        "authorization_url": "https://foursquare.com/oauth2/authenticate",
        "user_info_map": {"id": "response.user.id", "email": "response.user.contact.email", "name": "response.user.firstName", "picture": "response.user.photo"},
    },
    "goodreads": {
        "token_url": "https://www.goodreads.com/oauth/access_token",
        "user_info_url": "https://www.goodreads.com/api/auth_user",
        "authorization_url": "https://www.goodreads.com/oauth/authorize",
        "user_info_map": {"id": "user@id", "email": None, "name": "user@name", "picture": None},
    },
    "buffer": {
        "token_url": "https://api.bufferapp.com/1/oauth2/token.json",
        "user_info_url": "https://api.bufferapp.com/1/user.json",
        "authorization_url": "https://bufferapp.com/oauth2/authorize",
        "user_info_map": {"id": "id", "email": None, "name": "name", "picture": None},
    },
    "podio": {
        "token_url": "https://api.podio.com/oauth/token",
        "user_info_url": "https://api.podio.com/user/status",
        "authorization_url": "https://podio.com/oauth/authorize",
        "user_info_map": {"id": "user.user_id", "email": "user.mail", "name": "user.name", "picture": "user.image"},
    },
    "basecamp": {
        "token_url": "https://launchpad.37signals.com/authorization/token",
        "user_info_url": "https://launchpad.37signals.com/authorization.json",
        "authorization_url": "https://launchpad.37signals.com/authorization/new",
        "user_info_map": {"id": "identity.id", "email": "identity.email_address", "name": "identity.first_name", "picture": None},
    },
    "xero": {
        "token_url": "https://identity.xero.com/connect/token",
        "user_info_url": "https://api.xero.com/api.xro/2.0/Users",
        "authorization_url": "https://login.xero.com/identity/connect/authorize",
        "user_info_map": {"id": "Users[0].UserID", "email": "Users[0].EmailAddress", "name": "Users[0].FirstName", "picture": None},
    },
    "hubspot": {
        "token_url": "https://api.hubapi.com/oauth/v1/token",
        "user_info_url": "https://api.hubapi.com/oauth/v1/access-tokens/{token}",
        "authorization_url": "https://app.hubspot.com/oauth/authorize",
        "user_info_map": {"id": "user_id", "email": "user", "name": None, "picture": None},
    },
    "mailchimp": {
        "token_url": "https://login.mailchimp.com/oauth2/token",
        "user_info_url": "https://login.mailchimp.com/oauth2/metadata",
        "authorization_url": "https://login.mailchimp.com/oauth2/authorize",
        "user_info_map": {"id": "login.login_id", "email": "login.email", "name": None, "picture": None},
    },
    "shopify": {
        "token_url": "https://{shop}.myshopify.com/admin/oauth/access_token",
        "user_info_url": "https://{shop}.myshopify.com/admin/api/2024-01/shop.json",
        "authorization_url": "https://{shop}.myshopify.com/admin/oauth/authorize",
        "user_info_map": {"id": "shop.id", "email": "shop.email", "name": "shop.name", "picture": None},
    },
    "quickbooks": {
        "token_url": "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
        "user_info_url": "https://accounts.intuit.com/v1/openid_connect/userinfo",
        "authorization_url": "https://appcenter.intuit.com/connect/oauth2",
        "user_info_map": {"id": "sub", "email": "email", "name": "givenName", "picture": None},
    },
    "stripe": {
        "token_url": "https://connect.stripe.com/oauth/token",
        "user_info_url": "https://api.stripe.com/v1/account",
        "authorization_url": "https://connect.stripe.com/oauth/authorize",
        "user_info_map": {"id": "id", "email": "email", "name": "business_profile.support_email", "picture": None},
    },
    "twilio": {
        "token_url": "https://auth.twilio.com/oauth2/token",
        "user_info_url": "https://auth.twilio.com/oauth2/userinfo",
        "authorization_url": "https://auth.twilio.com/oauth2/authorize",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": None},
    },
    "openid": {
        "token_url": "{issuer}/oauth2/token",
        "user_info_url": "{issuer}/oauth2/userinfo",
        "authorization_url": "{issuer}/oauth2/authorize",
        "user_info_map": {"id": "sub", "email": "email", "name": "name", "picture": "picture"},
    },
}
